package org.kopuz.transfer_zone.entity;

import java.util.List;
import java.util.Set;

public class TeamList {
    public static final List<String> teams = List.of(
            // Türkiye
            "fenerbahce", "fenerbahçe",
            "galatasaray", "galatasaray",
            "besiktas", "beşiktaş",
            "trabzonspor", "trabzonspor",
            "basaksehir", "başakşehir",
            "bursaspor", "bursaspor",
            "goztepe", "göztepe",
            "altay", "altay",
            "konyaspor", "konyaspor",
            "sivasspor", "sivasspor",

            // England
            "manchester united",
            "manchester city",
            "liverpool",
            "chelsea",
            "arsenal",
            "tottenham hotspur",
            "newcastle united",
            "aston villa",
            "leicester city",
            "everton",

            // Spain
            "real madrid",
            "barcelona",
            "atletico madrid",
            "sevilla",
            "valencia",
            "villarreal",
            "real sociedad",
            "real betis",
            "athletic bilbao",
            "celta vigo",

            // Germany
            "bayern munich",
            "borussia dortmund",
            "rb leipzig",
            "bayer leverkusen",
            "schalke 04",
            "wolfsburg",
            "eintracht frankfurt",
            "mainz 05",
            "hertha berlin",
            "stuttgart",

            // Italy
            "juventus",
            "ac milan",
            "inter milan",
            "as roma",
            "napoli",
            "lazio",
            "fiorentina",
            "atalanta",
            "torino",
            "udinese",

            // France
            "paris saint-germain",
            "marseille",
            "lyon",
            "monaco",
            "lille",
            "rennes",
            "nice",
            "nantes",
            "bordeaux",
            "toulouse",

            // Netherlands
            "ajax",
            "psv eindhoven",
            "feyenoord",
            "az alkmaar",
            "twente",
            "heerenveen",
            "utrecht",
            "groningen",
            "vitese",
            "sparta rotterdam",

            // Portugal
            "benfica",
            "porto",
            "sporting lisbon",
            "braga",
            "guimaraes",
            "rio ave",
            "boavista",
            "maritimo",
            "estoril",
            "famalicao",

            // Brazil
            "flamengo",
            "palmeiras",
            "corinthians",
            "sao paulo",
            "santos",
            "gremio",
            "internacional",
            "botafogo",
            "vasco da gama",
            "cruzeiro",

            // Argentina
            "boca juniors",
            "river plate",
            "independiente",
            "racing club",
            "san lorenzo",
            "velez sarsfield",
            "newell's old boys",
            "rosario central",
            "huracan",
            "lanus",

            // Rest of World
            "celtic",
            "rangers",
            "galaxy",
            "lafc",
            "new york red bulls",
            "toronto fc",
            "club america",
            "tigres uanl",
            "monterrey",
            "al hilal",
            "al nassr",
            "shanghai port",
            "guangzhou evergrande",
            "beijing guoan",
            "jeonbuk hyundai",
            "ulsan hyundai",
            "suwon samsung",
            "kashima antlers",
            "urawa red diamonds",
            "gamba osaka",
            "sydney fc",
            "melbourne victory",
            "auckland city",
            "zamalek",
            "al ahly",
            "esperance",
            "tp mazembe",
            "kaizer chiefs",
            "mamelodi sundowns",
            "dinamo zagreb",
            "red star belgrade",
            "partizan belgrade",
            "apoel nicosia",
            "legia warsaw",
            "slavia prague",
            "rapid vienna",
            "ferencvaros",
            "basel",
            "young boys",
            "shakhtar donetsk",
            "dynamo kyiv",
            "zenit",
            "spartak moscow",
            "cska moscow",
            "lokomotiv moscow",
            "galway united",
            "bohemians",
            "hjk helsinki",
            "rosenborg",
            "malmo ff",
            "copenhagen",
            "brondby",
            "aek athens",
            "olympiakos",
            "panathinaikos",
            "besiktas", "beşiktaş",
            "galatasaray", "galatasaray",
            "fenerbahce", "fenerbahçe",
            "trabzonspor", "trabzonspor",
            "istanbulspor", "istanbulspor",
            "kasımpasa", "kasimpasa",
            "alanyaspor", "alanyaspor",
            "adanaspor", "adanaspor",
            "samsunspor", "samsunspor",
            "ankaragucu", "ankaragücü",
            "rizespor", "rizespor",
            "karagumruk", "karagümrük"
    );
}
